CREATE TABLE `department` (
  `DEPT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DEPT_NAME` varchar(50) NOT NULL DEFAULT '',
  `TEL_NO` varchar(50) NOT NULL DEFAULT '',
  `FAX_NO` varchar(50) NOT NULL DEFAULT '',
  `DEPT_ADDRESS` varchar(100) NOT NULL,
  `DEPT_NO` varchar(200) NOT NULL DEFAULT '0',
  `DEPT_PARENT` int(11) NOT NULL DEFAULT '0',
  `MANAGER` text NOT NULL,
  `ASSISTANT_ID` text NOT NULL,
  `LEADER1` text NOT NULL,
  `LEADER2` text NOT NULL,
  `DEPT_FUNC` text NOT NULL,
  `IS_ORG` char(1) NOT NULL DEFAULT '0',
  `ORG_ADMIN` varchar(200) NOT NULL,
  PRIMARY KEY (`DEPT_ID`),
  KEY `DEPT_NO` (`DEPT_NO`),
  KEY `DEPT_PARENT` (`DEPT_PARENT`)
) ;