CREATE TABLE IF NOT EXISTS `sms` (
  `SMS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TO_ID` varchar(20) NOT NULL DEFAULT '',
  `REMIND_FLAG` char(1) NOT NULL DEFAULT '',
  `DELETE_FLAG` char(1) NOT NULL DEFAULT '0',
  `BODY_ID` int(11) NOT NULL DEFAULT '0',
  `REMIND_TIME` int(11) NOT NULL DEFAULT '0',
  UNIQUE KEY `ID` (`SMS_ID`),
  KEY `TO_ID` (`TO_ID`),
  KEY `BODY_ID` (`BODY_ID`),
  KEY `REMIND_TIME` (`REMIND_TIME`)
);